name: "Develop"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CORE_SDK_VERSION: 5.0.100
  MYGET_ACCESS_TOKEN: ${{ secrets.MYGET_ACCESS_TOKEN }}
  MYGET_SOURCE_URL: 'https://www.myget.org/F/lithiumtoast/api/v3/index.json'

on:
  push:
    branches: [develop]
    tags: [v*]

jobs:

  version-job:
    name: "GitVersion"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Git repository"
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_REF }}

    - name: "Fetch all history for all tags and branches"
      run: git fetch --prune --unshallow

    - name: "Install GitVersion"
      uses: gittools/actions/gitversion/setup@v0.9.6
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true # workaround for https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ until the execute action is updated
      with:
        versionSpec: '5.x'
          
    - name: "Use GitVersion"
      uses: gittools/actions/gitversion/execute@v0.9.6

    - run: echo "$GitVersion_NuGetVersionV2" >> nuget-version.txt

    - name: 'Upload NuGetVersion version artifact'
      uses: actions/upload-artifact@v2
      with:
        name: nuget-version
        path: nuget-version.txt

  build-native-job:
    name: "Build native libraries ${{ matrix.platform.rid }}"
    needs: [version-job]
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows (x64), os: ubuntu-latest, rid: win-x64 }
        - { name: Linux (x64), os: ubuntu-latest, rid: linux-x64 }
        - { name: macOS (x64), os: macos-latest, rid: osx-x64 }
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        ref: ${{ env.GITHUB_REF }}
        submodules: 'recursive'

    - name: "Build native libraries (Windows)"
      if: ${{ startsWith(matrix.platform.rid, 'win') }}
      shell: bash
      run: sudo apt-get update -y && sudo apt-get install -y mingw-w64 && ./library.sh microsoft

    - name: "Build native libraries (Unix)"
      if: ${{ !(startsWith(matrix.platform.rid, 'win')) }}
      shell: bash
      run: ./library.sh

    - name: "Upload native libraries"
      uses: actions/upload-artifact@v2
      with:
        name: "native-libraries-${{ matrix.platform.rid }}"
        path: './lib'

  build-dotnet-job:
    name: "Build .NET solution ${{ matrix.platform.rid }}"
    needs: [build-native-job]
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows (x64), os: windows-latest, rid: win-x64 }
        - { name: Linux (x64), os: ubuntu-latest, rid: linux-x64 }
        - { name: macOS (x64), os: macos-latest, rid: osx-x64 }
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        ref: ${{ env.GITHUB_REF }}
        submodules: 'recursive'

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_SDK_VERSION }}'

    - name: "Download native libraries"
      uses: actions/download-artifact@v1
      with:
        name: "native-libraries-${{ matrix.platform.rid }}"
        path: './lib'

    - name: "Download version artifact"
      uses: actions/download-artifact@v2
      with:
        name: nuget-version

    - name: "Read Version"
      id: version
      shell: bash
      run: |
        echo "VERSION=$(cat nuget-version.txt)" >> $GITHUB_ENV

    - name: "Print Version"
      shell: bash
      run: |
        echo $VERSION

    - name: "Restore solution"
      run: dotnet restore --nologo

    - name: "Build solution"
      run: dotnet build --nologo --configuration Release /p:Version='${{ env.VERSION }}' --no-restore

    - name: "Test solution"
      run: dotnet test --nologo --configuration Release --no-build

    - name: "Pack solution"
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack --nologo --output "./nuget-packages-packed" --verbosity minimal --configuration Release --no-build -p:PackageVersion='${{ env.VERSION }}'

    - name: "Upload packages"
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages-packed
        path: './nuget-packages-packed/*/**'

  deploy-job:
    name: "Deploy"
    needs: [build-dotnet-job]
    runs-on: ubuntu-latest
    steps:

    - name: "Setup .NET Core CLI"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_CORE_SDK_VERSION }}'

    - name: "Download NuGet Packages"
      uses: actions/download-artifact@v1
      with:
        name: nuget-packages-packed
        path: './nuget-packages-packed'

    - name: "Echo Packages"
      run: find ./nuget-packages-packed/ -not -type d -exec basename {} \;
      
    - name: "Add Packages Source: MyGet"
      run: dotnet nuget add source $MYGET_SOURCE_URL --name "MyGet"
 
    - name: "Upload Packages: MyGet"
      run: dotnet nuget push "./**/*.nupkg" --source "MyGet" --skip-duplicate --api-key $MYGET_ACCESS_TOKEN













